name: invest_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf

    - family: Sallim
      fonts:
        - asset: assets/fonts/SallimSignature.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    
    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf


